// Domain model — core EntitySmith types.

use serde::{Deserialize, Serialize};

/// A stable identifier used across all domain objects.
pub type EntityId = String;

/// Top-level project metadata. Persisted in the .entitysmith project file.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProjectState {
    pub id: EntityId,
    pub name: String,
    pub version: u32,
    pub created_at: String,
    pub updated_at: String,
}

/// Describes a registered data source.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceDescriptor {
    pub id: EntityId,
    pub project_id: EntityId,
    pub name: String,
    pub kind: SourceKind,
    pub path: Option<String>,
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SourceKind {
    SqliteFile,
    JsonFile,
    CsvFile,
    MarkdownFolder,
    PdfFile,
    Url,
    Postgres,
    Mysql,
}

/// A canonical entity type in the schema graph.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EntityType {
    pub id: EntityId,
    pub project_id: EntityId,
    pub name: String,
    pub label: Option<String>,
    pub description: Option<String>,
    pub created_at: String,
}

/// A relationship between two entity types.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Relationship {
    pub id: EntityId,
    pub project_id: EntityId,
    pub source_entity_type_id: EntityId,
    pub target_entity_type_id: EntityId,
    pub predicate: String,
    pub cardinality: Option<String>,
    pub created_at: String,
}

/// A relationship or schema proposal generated by the system.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Proposal {
    pub id: EntityId,
    pub project_id: EntityId,
    pub kind: ProposalKind,
    pub status: ProposalStatus,
    pub confidence: f64,
    pub origin: ProposalOrigin,
    pub evidence: serde_json::Value,
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProposalKind {
    ForeignKey,
    SoftForeignKey,
    ColumnNameSimilarity,
    SampleValueOverlap,
    EmbeddingSimilarity,
    LlmReasoning,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProposalStatus {
    Pending,
    Accepted,
    Rejected,
    Modified,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProposalOrigin {
    DeclaredFk,
    Heuristic,
    Embedding,
    Llm,
}

/// Provenance record attached to decisions and proposals.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProvenanceRecord {
    pub id: EntityId,
    pub object_id: EntityId,
    pub object_kind: String,
    pub action: String,
    pub actor: String,
    pub detail: serde_json::Value,
    pub created_at: String,
}

/// Tracks the lifecycle of a background job.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JobStatus {
    pub id: EntityId,
    pub kind: String,
    pub status: JobState,
    pub progress: Option<f64>,
    pub message: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum JobState {
    Queued,
    Running,
    Completed,
    Failed,
    Canceled,
}

/// A validation issue found during graph validation.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ValidationIssue {
    pub id: EntityId,
    pub kind: ValidationKind,
    pub message: String,
    pub object_id: Option<EntityId>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ValidationKind {
    Error,
    Warning,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ExportFormat {
    Turtle,
    JsonLd,
    GraphMl,
    Mermaid,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum UriStrategy {
    UuidV4,
    UlidBased,
    ColumnBased { column: String, prefix: String },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConflictPolicy {
    PreferSourceA,
    PreferSourceB,
    PreferNonNull,
    PreferMostRecent,
    KeepBoth,
}
